### ISSUE TITLE
forcefeedback.exe not working for Xbox controller 

### ISSUE THREAD

**Issue by car10s2431** [bobhelander/EDForceFeedback#17]
I've followed all the instructions for this to work but for some reason, I get no vibration from doing any actions in Elite Dangerous.

**Comment by bobhelander** [comment]
Please verify that the joystick's force feedback functions work by using the ffedit.exe application included in the download (it is included in a sub folder with the force feedback.exe app).

Bob

**Comment by car10s2431** [comment]
I opened the ffedit.exe application and I got a message saying “could not find a force feedback device”

**Comment by bobhelander** [comment]
What device do you have?

**Comment by car10s2431** [comment]
I’m using a Lenovo legion 5 AMD Ryzen 7 5800- NVIDIA GeForce RTX 3050 Ti - 8GB memory

**Comment by bobhelander** [comment]
I'm sorry for the confusion.  What force feedback joystick device are you attempting to use?

**Comment by car10s2431** [comment]
Oh I’m sorry I thought that would be considered the Xbox one controller? Or would I need a completed different thing for it to work? I honestly have no clue what I need I just want the vibration feature to work for elite 😅

**Comment by bobhelander** [comment]
Thank you.  I believe I have the instructions in the readme file.  You will need another software package installed (the link is in the instructions).  Once you have that, rename the settings file that has the .Xbox extension to settings.json. Please follow the instructions, I am not anywhere where I can access the files and instructions so, my steps are from memory and it has been at least a year since I have tested the steps.  I can test again tomorrow evening if you are still unable to get it to work.

Thank you,
Bob

**Comment by car10s2431** [comment]
Alright, I’ll test it out and let you know if it works! Thank you again and sorry for the confusion!

**Comment by car10s2431** [comment]
09:28:02 info: EliteAPI.EliteDangerousApi[0] Initializing EliteAPI v3.0.0-alpha.1188
09:28:02 dbug: EliteAPI.Event.Processor.EventsEventProcessor[0] Detecting event handlers
09:28:02 dbug: EliteAPI.Event.Processor.EventsEventProcessor[0] 230 event-handlers were registered in 20ms
09:28:02 dbug: EliteAPI.Event.Processor.AttributeEventProcessor[0] Detecting event handlers
09:28:02 dbug: EliteAPI.Event.Processor.AttributeEventProcessor[0] 0 event-handlers were registered in 0ms
09:28:02 dbug: EliteAPI.Journal.Provider.JournalProvider[0] No configuration value for JournalPath set, defaulting to standard
09:28:02 info: EliteAPI.EliteDangerousApi[0] Setting journal directory to C:\Users\elcar\Saved Games\Frontier Developments\Elite Dangerous
09:28:02 dbug: EliteAPI.Options.Directory.Abstractions.IOptionsDirectoryProvider[0] No configuration value for OptionsPath set, defaulting to standard
09:28:02 info: EliteAPI.EliteDangerousApi[0] Setting options directory to C:\Users\elcar\AppData\Local\Frontier Developments\Elite Dangerous\Options
09:28:02 info: EliteAPI.EliteDangerousApi[0] Setting journal file to Journal.2022-09-03T205149.01.log
09:28:02 dbug: EliteAPI.Status.Provider.StatusProvider[0] Could not find a support file EliteAPI.Exceptions.SupportFileNotFoundException: The Market.json could not be found
09:28:02 dbug: EliteAPI.EliteDangerousApi[0] Market.json file support has been disabled EliteAPI.Exceptions.MarketFileNotFoundException: Could not find the Market.json file ---> EliteAPI.Exceptions.SupportFileNotFoundException: The Market.json could not be found    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.Status.Provider.StatusProvider.<FindMarketFile>d__3.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\Status\Provider\StatusProvider.cs:line 33    --- End of inner exception stack trace ---    at EliteAPI.Status.Provider.StatusProvider.<FindMarketFile>d__3.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\Status\Provider\StatusProvider.cs:line 34 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 405
09:28:02 dbug: EliteAPI.EliteDangerousApi[0] EliteAPI has initialized
09:28:02 info: EliteAPI.EliteDangerousApi[0] EliteAPI has started
09:28:02 dbug: EliteAPI.Status.Provider.StatusProvider[0] Could not find a support file EliteAPI.Exceptions.SupportFileNotFoundException: The Shipyard.json could not be found
09:28:02 dbug: EliteAPI.EliteDangerousApi[0] Shipyard.json file support has been disabled EliteAPI.Exceptions.ShipyardFileNotFoundException: Could not find the Shipyard.json file ---> EliteAPI.Exceptions.SupportFileNotFoundException: The Shipyard.json could not be found    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.Status.Provider.StatusProvider.<FindShipyardFile>d__6.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\Status\Provider\StatusProvider.cs:line 54    --- End of inner exception stack trace ---    at EliteAPI.Status.Provider.StatusProvider.<FindShipyardFile>d__6.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\Status\Provider\StatusProvider.cs:line 55 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 411
Event Status.FlightAssist:True
Event EliteAPI.Event.Models.FileheaderEvent
Event EliteAPI.Event.Models.CommanderEvent
Event EliteAPI.Event.Models.MaterialsEvent
Event EliteAPI.Event.Models.RankEvent
Event EliteAPI.Event.Models.ProgressEvent
Event EliteAPI.Event.Models.ReputationEvent
Event EliteAPI.Event.Models.EngineerProgressEvent
Event EliteAPI.Event.Models.LoadGameEvent
Event EliteAPI.Event.Models.StatisticsEvent
Event EliteAPI.Event.Models.LocationEvent
Event EliteAPI.Event.Models.MusicEvent
Event EliteAPI.Event.Models.ShipLockerEvent
Event EliteAPI.Event.Models.MissionsEvent
Event EliteAPI.Event.Models.LoadoutEvent
Event EliteAPI.Event.Models.MusicEvent
Event EliteAPI.Event.Models.CargoEvent
Event EliteAPI.Event.Models.MusicEvent
Event EliteAPI.Event.Models.StartJumpEvent
Event EliteAPI.Event.Models.MusicEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
Event EliteAPI.Event.Models.SupercruiseEntryEvent
Event EliteAPI.Event.Models.ShipLockerEvent
Event EliteAPI.Event.Models.MusicEvent
Event EliteAPI.Event.Models.SupercruiseExitEvent
Event EliteAPI.Event.Models.ShipLockerEvent
Event EliteAPI.Event.Models.MusicEvent
Event EliteAPI.Event.Models.ShutdownEvent
09:28:02 info: EliteAPI.EliteDangerousApi[0] EliteAPI has caught up to current session
09:28:03 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:03 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:04 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:04 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:05 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:05 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:06 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:06 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:07 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:08 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276
09:28:08 warn: EliteAPI.EliteDangerousApi[0] Could not do tick System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<DoTick>d__136.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 276

okay so i downloaded the other software package needed and when I ran it under ffedit.exe it worked! Although when I run the Force Feedback.exe with elite dangerous, I get no response. This is whats showing up on the console.

**Comment by bobhelander** [comment]
I have uploaded a new version (3.0).  I am still unable to test the xbox one controller locally.  Please have patience, I am looking for the required hardware.

Bob

**Comment by car10s2431** [comment]
Absolutely no worries! Take all the time you need, I really appreciate all the help!

**Comment by bobhelander** [comment]
I have tested the build and it does work.  Please let me know if you have any additional issues.

Bob

**Comment by car10s2431** [comment]
Thank you again for all the help! I've been trying to make it work for a while now but I'm not sure what I'm doing wrong. I have the EliteAPI downloaded but whenever I open the EDforcefeedback.exe, this is what I get:

Using setting file: C:\Users\elcar\Desktop\EDForceFeedback (1)\settings.json
05:55:48 dbug: Journals.Client[0] DeviceName: Mouse: ProductGuid 6f1d2b60-d5a0-11cf-bfc7-444553540000
05:55:48 dbug: Journals.Client[0] DeviceName: Keyboard: ProductGuid 6f1d2b61-d5a0-11cf-bfc7-444553540000
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: HIDI2C Device: ProductGuid 31dd04f3-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: HIDI2C Device: ProductGuid 31dd04f3-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: Controller (Xbox One For Windows): ProductGuid 02ff045e-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:55:48 dbug: Journals.Client[0] No matching Joystick/Gamepad/Wheel found. {deviceInstance.ProductName} {productGuid}
05:55:48 fail: Journals.Client[0] Device Initialization failed: 001b045e-0000-0000-0000-504944564944: SideWinder Force Feedback 2 Joystick
05:55:48 info: EliteAPI.EliteDangerousApi[0] Initializing EliteAPI v3.0.0-alpha.1188
05:55:48 dbug: EliteAPI.Event.Processor.EventsEventProcessor[0] Detecting event handlers
05:55:48 dbug: EliteAPI.Event.Processor.EventsEventProcessor[0] 230 event-handlers were registered in 48ms
05:55:48 dbug: EliteAPI.Event.Processor.AttributeEventProcessor[0] Detecting event handlers
05:55:48 dbug: EliteAPI.Event.Processor.AttributeEventProcessor[0] 0 event-handlers were registered in 1ms
05:55:48 dbug: EliteAPI.Journal.Provider.JournalProvider[0] No configuration value for JournalPath set, defaulting to standard
05:55:48 info: EliteAPI.EliteDangerousApi[0] Setting journal directory to C:\Users\elcar\Saved Games\Frontier Developments\Elite Dangerous
05:55:48 dbug: EliteAPI.Options.Directory.Abstractions.IOptionsDirectoryProvider[0] No configuration value for OptionsPath set, defaulting to standard
05:55:48 info: EliteAPI.EliteDangerousApi[0] Setting options directory to C:\Users\elcar\AppData\Local\Frontier Developments\Elite Dangerous\Options
05:55:48 info: EliteAPI.EliteDangerousApi[0] Setting journal file to Journal.2022-09-09T172041.01.log
05:55:48 fail: EliteAPI.EliteDangerousApi[0] EliteAPI could not be initialized System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<InitializeAsync>d__121.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 197
05:55:49 crit: EliteAPI.EliteDangerousApi[0] EliteAPI could not be started System.NullReferenceException: Object reference not set to an instance of an object.    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at EliteAPI.EliteDangerousApi.<InitializeAsync>d__121.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 197

**Comment by bobhelander** [comment]
There are two problems here:
> 05:55:48 fail: Journals.Client[0] Device Initialization failed: 001b045e-0000-0000-0000-504944564944: SideWinder Force Feedback 2 Joystick
It is using the wrong configuration file.

And 

>05:55:48 fail: EliteAPI.EliteDangerousApi[0] EliteAPI could not be initialized System.NullReferenceException: Object reference not set to an instance of an object. at EliteAPI.EliteDangerousApi.d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 475

A 3rd party library I am using is complaining about your keybindings file.  

I have published a new version of the application that has the xbox controller as the default controller in the settings.  It also attempts to keep the program from crashing when the bindings file is not known.  I am unsure if this state will cause more problems later.  I will continue to look to see if this has been solved in the 3rd party library.

Go ahead and try the new version and I am sorry that this is not working easily for you.

Bob

**Comment by car10s2431** [comment]
So, everything seems to be working perfectly! The only thing I see on the console is a warning that I'm not sure will interfere with the program. Other than that, everything seems to be going well! Thank you again for all the help :D

Here's is what I'm seeing on the console:

Using setting file: C:\Users\elcar\Desktop\EDForceFeedback (2)\Release\settings.json
05:39:36 dbug: Journals.Client[0] DeviceName: Mouse: ProductGuid 6f1d2b60-d5a0-11cf-bfc7-444553540000
05:39:36 dbug: Journals.Client[0] DeviceName: Keyboard: ProductGuid 6f1d2b61-d5a0-11cf-bfc7-444553540000
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: HIDI2C Device: ProductGuid 31dd04f3-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8295): ProductGuid c965048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: HIDI2C Device: ProductGuid 31dd04f3-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: ITE Device(8910): ProductGuid c101048d-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] DeviceName: Controller (Xbox One For Windows): ProductGuid 02ff045e-0000-0000-0000-504944564944
05:39:36 dbug: Journals.Client[0] Found Joystick/Gamepad Controller (Xbox One For Windows)
05:39:36 dbug: Journals.Client[0] Effect available Constant Force
05:39:36 dbug: Journals.Client[0] Effect available Ramp Force
05:39:36 dbug: Journals.Client[0] Effect available Square
05:39:36 dbug: Journals.Client[0] Effect available Sine
05:39:36 dbug: Journals.Client[0] Effect available Triangle
05:39:36 dbug: Journals.Client[0] Effect available Sawtooth Up
05:39:36 dbug: Journals.Client[0] Effect available Sawtooth Down
05:39:36 dbug: Journals.Client[0] Effect available Spring
05:39:36 dbug: Journals.Client[0] Effect available Damper
05:39:36 dbug: Journals.Client[0] Effect available Inertia
05:39:36 dbug: Journals.Client[0] Effect available Friction
05:39:36 dbug: Journals.Client[0] Effect available Custom Force
05:39:36 dbug: Journals.Client[0] File Effect available Cargo.ffe
05:39:36 dbug: Journals.Client[0] File Effect available CenterSpringXY.ffe
05:39:36 dbug: Journals.Client[0] File Effect available Damper.ffe
05:39:36 dbug: Journals.Client[0] File Effect available Dock.ffe
05:39:36 dbug: Journals.Client[0] File Effect available FEdit1.ffe
05:39:36 dbug: Journals.Client[0] File Effect available Gear.ffe
05:39:36 dbug: Journals.Client[0] File Effect available Hardpoints.ffe
05:39:36 dbug: Journals.Client[0] File Effect available Landed.ffe
05:39:36 dbug: Journals.Client[0] File Effect available Vibrate.ffe
05:39:36 dbug: Journals.Client[0] File Effect available VibrateSide.ffe
05:39:36 info: EliteAPI.EliteDangerousApi[0] Initializing EliteAPI v3.0.0-alpha.1188
05:39:36 dbug: EliteAPI.Event.Processor.EventsEventProcessor[0] Detecting event handlers
05:39:36 dbug: EliteAPI.Event.Processor.EventsEventProcessor[0] 230 event-handlers were registered in 20ms
05:39:36 dbug: EliteAPI.Event.Processor.AttributeEventProcessor[0] Detecting event handlers
05:39:36 dbug: EliteAPI.Event.Processor.AttributeEventProcessor[0] 0 event-handlers were registered in 0ms
05:39:36 dbug: EliteAPI.Journal.Provider.JournalProvider[0] No configuration value for JournalPath set, defaulting to standard
05:39:36 info: EliteAPI.EliteDangerousApi[0] Setting journal directory to C:\Users\elcar\Saved Games\Frontier Developments\Elite Dangerous
05:39:36 dbug: EliteAPI.Options.Directory.Abstractions.IOptionsDirectoryProvider[0] No configuration value for OptionsPath set, defaulting to standard
05:39:36 info: EliteAPI.EliteDangerousApi[0] Setting options directory to C:\Users\elcar\AppData\Local\Frontier Developments\Elite Dangerous\Options
05:39:36 info: EliteAPI.EliteDangerousApi[0] Setting journal file to Journal.2022-09-10T132859.01.log
05:39:36 warn: EliteAPI.EliteDangerousApi[0] Cannot use bindings preset (null) EliteAPI.Exceptions.BindingsNotFoundException: Could not find a bindings file    at EliteAPI.Options.Provider.OptionsProvider.FindActiveBindingsFile(DirectoryInfo optionsDirectory) in E:\workspace\elite\EliteAPI\EliteAPI\Options\Provider\OptionsProvider.cs:line 53    at EliteAPI.EliteDangerousApi.<SetSupportFiles>d__143.MoveNext() in E:\workspace\elite\EliteAPI\EliteAPI\EliteDangerousApi.cs:line 424
05:39:36 dbug: EliteAPI.EliteDangerousApi[0] EliteAPI has initialized
05:39:36 info: EliteAPI.EliteDangerousApi[0] EliteAPI has started
05:39:36 dbug: Journals.Client[0] Event Status.FlightAssist:True
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.FileheaderEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.CommanderEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.MaterialsEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.RankEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ProgressEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ReputationEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.EngineerProgressEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.LoadGameEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.StatisticsEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ReceiveTextEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.LocationEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.MusicEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ShipLockerEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.MissionsEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.LoadoutEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.MusicEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.CargoEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.StartJumpEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.FssSignalDiscoveredEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.SupercruiseEntryEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ShipLockerEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.MusicEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.SupercruiseExitEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ShipLockerEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ApproachBodyEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.MusicEvent
05:39:36 dbug: Journals.Client[0] Event EliteAPI.Event.Models.ShutdownEvent
05:39:36 info: EliteAPI.EliteDangerousApi[0] EliteAPI has caught up to current session
